services:

  partstracker:
    image: ${DOCKER_REGISTRY-}partstracker
    build:
      context: .
      dockerfile: PartsTracker/Dockerfile
    depends_on:
        postgres:
          condition: service_healthy

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: partsuser
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: InventoryDb
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U partsuser"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  pgdata: