name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: src/PartsTracker.WebApi
          file: Dockerfile
          push: true
          tags: rudigrobler/your-image:latest
      - name: Build and push Docker image (WebApi)
        uses: docker/build-push-action@v5
        with:
          context: src/PartsTracker.WebApi
          file: Dockerfile
          push: true
          tags: rudigrobler/partstrackerwebapi:latest
      - name: Build and push Docker image (UI)
        uses: docker/build-push-action@v5
        with:
          context: rc/PartsTracker.UI/partstracker.u
          file: Dockerfile
          push: true
          tags: rudigrobler/partstrackerui:latest
