name: PartsTracker Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet build ./PartsTracker.sln --configuration Release
    
    - name: Test with dotnet
      run: dotnet test ./PartsTracker.sln --configuration Release
